# Generated by Django 4.1.13 on 2026-05-09 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')]),
        ),
    ]
